-- Script de criação do esquema com todas as tabelas e relacionamentos reais
-- Compatível com H2 Database

-- Ordem de criação: tabelas dependidas primeiro

CREATE TABLE IF NOT EXISTS curso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS categoria_usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL UNIQUE
);

-- Herança SINGLE_TABLE para Usuario com coluna discriminadora "tipo"
CREATE TABLE IF NOT EXISTS usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    cpf VARCHAR(11) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL,
    categoria_usuario_id BIGINT NOT NULL,
    curso_id BIGINT NOT NULL,
    suspenso_ate TIMESTAMP NULL,
    tipo VARCHAR(31),
    CONSTRAINT fk_usuario_categoria FOREIGN KEY (categoria_usuario_id)
        REFERENCES categoria_usuario(id),
    CONSTRAINT fk_usuario_curso FOREIGN KEY (curso_id)
        REFERENCES curso(id)
);

CREATE INDEX IF NOT EXISTS idx_usuario_cpf ON usuario(cpf);

-- Tabela de livros
CREATE TABLE IF NOT EXISTS livro (
    isbn VARCHAR(255) PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    autor VARCHAR(255) NOT NULL,
    editora VARCHAR(255) NOT NULL,
    edicao VARCHAR(255) NOT NULL,
    categoria_livro VARCHAR(64) NOT NULL,
    disponivel BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_livro_autor_edicao_editora UNIQUE (autor, edicao, editora)
);

-- Controle de exemplares (estoque)
CREATE TABLE IF NOT EXISTS estoque (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    livro_isbn VARCHAR(255),
    disponivel BOOLEAN DEFAULT TRUE,
    CONSTRAINT fk_estoque_livro FOREIGN KEY (livro_isbn)
        REFERENCES livro(isbn)
);

-- Empréstimos
CREATE TABLE IF NOT EXISTS emprestimo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    estoque_id BIGINT NOT NULL,
    data_emprestimo TIMESTAMP NOT NULL,
    data_devolucao TIMESTAMP NULL,
    data_entrega TIMESTAMP NULL,
    CONSTRAINT fk_emprestimo_usuario FOREIGN KEY (usuario_id)
        REFERENCES usuario(id),
    CONSTRAINT fk_emprestimo_estoque FOREIGN KEY (estoque_id)
        REFERENCES estoque(id)
);
